### ISSUE TITLE
3.x staging

### ISSUE THREAD

**Issue by nicolas377** [GeoFS-Extensions/autoland#80]
This issue will be a staging area for everything we're fixing in 3.x.
We'll probably clump multiple features into each update.
For new updates, add a comment to this issue, and we'll discuss and assign a update.
All feature lists are for the patch 0 (ex. 3.2.0) update.

Key for feature lists:
**MAJOR CHANGE**
_MINOR CHANGE_
<ins>BUGFIX</ins>

## 3.2.x
- Staging issue: #77
- Features list:
  - [x] **Optimized AP++ file size by loading nav data from chrome extension.** #42
  - [x] **Added support for GeoFS betas.**
  - [x] *Made sure scripts were injected in the right order.* #56
  - [x] *Made updates quieter.*
  - [x] <ins>Prevented scripts from injecting when there's no permission to do so.</ins>
  - [x] <ins>Fixed issue where VNAV broke below 1500 feet.</ins> https://github.com/GeoFS-Extensions/fmc-requirejs/issues/11

## 3.3.x
- Staging issue: not created yet
- Feature list:
    - [ ] **Add support for multiple key press keybinds** (new script: Keyboard Mapping)
    - [ ] **Move the entire codebase into one monorepo** #81 
    - [ ] *Condense storage into one entry* #36
    - [ ] <ins>FMC uses data from previous routes when fields are empty<ins> #87

**Comment by nicolas377** [comment]
Keyboard mapping will be included in 3.3.0, but there might be other features we want to add, so I haven't added it yet.
